### ISSUE TITLE
Setup Question

### ISSUE THREAD

**Issue by VikR1000** [mjwheatley/graphql-mongodb-subscriptions#43]
I'm using Meteor, which includes a MongoDB server. On localhost, the url for that mongo db is:

mongodb://localhost:3001/meteor

I'm trying this setup:

```
import { MongodbPubSub } from 'graphql-mongodb-subscriptions';
const { MongoClient } = require('mongodb');

const MONGO_URL = "mongodb://127.0.0.1:3001";
const mongoClient = new MongoClient(MONGO_URL, { useNewUrlParser: true, useUnifiedTopology: true });

async function startPubSub() {
    try {
        // Connect to the MongoDB server
        await mongoClient.connect();

        // Now that the client is connected, create the pubsub instance
        const pubsub = new MongodbPubSub({ connectionDb: mongoClient });

        // Subscribe to the "error" channel
        pubsub.subscribe("error", err => {
            console.log(`pubsub error: ${err.message}`);
        });

        console.log('PubSub initialized and connected to MongoDB');
    } catch (err) {
        console.error('Failed to initialize PubSub:', err);
    }
}

// Start the PubSub
startPubSub();
```
It runs without error, including printing:

> PubSub initialized and connected to MongoDB

But a moment later, It throws the following error:

```
TypeError: this.db.collections is not a function
    at Channel.init (/myLocalDevSystem/node_modules/@mawhea/mongopubsub/src/channel.ts:153:39)
    at Channel.listen (/myLocalDevSystem/node_modules/@mawhea/mongopubsub/src/channel.ts:110:18)
    at new Channel (/myLocalDevSystem/node_modules/@mawhea/mongopubsub/src/channel.ts:43:10)
    at new MongodbPubSub (/myLocalDevSystem/node_modules/graphql-mongodb-subscriptions/src/mongodb-pub-sub.ts:55:20)

```

What am I missing?

**Comment by mjwheatley** [comment]
I think you might need to change this
```
await mongoClient.connect();
const pubsub = new MongodbPubSub({connectionDb: mongoClient});
```
To this
```
const connectionDb = await mongoClient.connect();
const pubsub = new MongodbPubSub({connectionDb});
```

The `mongoClient.connect()` returns the initializes db objects 
https://mongodb.github.io/node-mongodb-native/api-generated/mongoclient.html

**Comment by VikR1000** [comment]
I updated it to:

```
import { MongodbPubSub } from 'graphql-mongodb-subscriptions';
const { MongoClient } = require('mongodb');

const MONGO_URL = "mongodb://127.0.0.1:3001";
const mongoClient = new MongoClient(MONGO_URL, { useNewUrlParser: true, useUnifiedTopology: true });

async function startPubSub() {
    try {
        const connectionDb = await mongoClient.connect();
        const pubsub = new MongodbPubSub({connectionDb});

        // Subscribe to the "error" channel
        pubsub.subscribe("error", err => {
            console.log(`pubsub error: ${err.message}`);
        });

        console.log('PubSub initialized and connected to MongoDB');
    } catch (err) {
        console.error('Failed to initialize PubSub:', err);
    }
}

startPubSub();
```

I'm still getting the same doggone error. 🤨

**Comment by VikR1000** [comment]
Here is a small demo project. The pubsub setup code is in `imports/apollo/resolvers.js`.  It can be started with `meteor run` in the terminal.

https://github.com/VikR1000/apollo-skeleton-suggested-minor-updates-v400

**Comment by VikR1000** [comment]
Here's a link to a small demo repo.  It can be started via `meteor run` in the terminal. The RedisPubSub setup code is in `imports/apollo/resolvers.js`.

https://github.com/VikR1000/apollo-skeleton-suggested-minor-updates-v400

**Comment by mjwheatley** [comment]
Here is my sample project using the `graphql-mongodb-subscriptions` package.  It uses `mongoose` but should be able to provide you some guidance in setting up the database collection.
https://github.com/mjwheatley/apollo-graphql-mongodb/blob/main/src/index.ts

If you are using Meteor, I'm curious why don't you just use Meteor's pub/sub feature? Are you using `Meteor.methods` as wells as a graphql endpoint all connected to the same database?

**Comment by VikR1000** [comment]
Great question! I'm using ApolloGraphQL for data and subscriptions.  This way I can use a relational database like PostGres, rather than MongoDB.  I'll check out the repo you provided!

**Comment by VikR1000** [comment]
That worked. Thanks very much, Matthew!
